FROM quay.io/quarkus/quarkus-micro-image:2.0
LABEL maintainer="Jaroslaw Stakun jstakun@redhat.com" \
      quarkus-version=2.12.1.Final \
      camel.version=3.18.1
WORKDIR /work/
COPY target/*-runner /work/application
RUN chmod 775 /work
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]